version: 1.0.{build}
image: Windows
build_script:
- cmd: "build.bat \nexit 0"
artifacts:
- path: '*.zip'
  name: GitHub
- path: version.info
  name: GitHub
deploy:
  - provider: GitHub
    auth_token:
      secure: aeboYYL1NtnEGgT+uR8t8NZZIrGtoxhqI95TCX2g7lYpO62JdiYkbVcq+9tKpecD
    draft: false
    prerelease: false
