version: 1.0.{build}
image: Visual Studio 2019
before_build:
- cmd: C:\projects\lumaca-setup\system\scripts\shared-variables.cmd
artifacts:
- path: '*.zip'
  name: GitHub
- path: version.info
  name: GitHub
deploy:
  - provider: GitHub
    auth_token:
      secure: aeboYYL1NtnEGgT+uR8t8NZZIrGtoxhqI95TCX2g7lYpO62JdiYkbVcq+9tKpecD
    draft: false
    prerelease: false
